### ISSUE TITLE
test demo

### ISSUE THREAD

**Issue by liushaoqian** [dynamiclu/Langchain-ChatBI#1]
你好，请问一下这个里面的question_answer.txt是不是对格式有要求啊，而且你的示例数据是空的，根本就没有demo做测试啊

**Comment by dynamiclu** [comment]
question_answer.txt是向量语料，用来召回的，不一定要结构化的格式，重点是语料准确。 数据表都是跟具体的业务相关，也可自己造demo数据，我找时间给弄些。

**Comment by liushaoqian** [comment]
我每次上传的时候总是出错，所以问问



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dynamiclu/Langchain-ChatBI] test demo (Issue #1)




 
question_answer.txt是向量语料，用来召回的，不一定要结构化的格式，重点是语料准确。 数据表都是跟具体的业务相关，也可自己造demo数据，我找时间给弄些。

**Comment by dynamiclu** [comment]
上传文件debug一下os.path，可能跟IDE或python环境变量有关

**Comment by dynamiclu** [comment]
刚更新了demo数据，欢迎试用

**Comment by liushaoqian** [comment]
好的，我看看



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 21, 2024 00:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [dynamiclu/Langchain-ChatBI] test demo (Issue #1)




 
刚更新了demo数据，欢迎试用
